/* eslint-disable */
// Generated by Wrangler by running `wrangler types worker-configuration.d.ts --config dist/server/wrangler.json --include-runtime false` (hash: 097708e8d377f8d555eca2889119e86d)
interface __BaseEnv_Env {
	EMAIL_FILES: R2Bucket;
	DB: D1Database;
	AI: Ai;
	ASSETS: Fetcher;
	CRM_AUTH_USERNAME: "mai";
}
declare namespace Cloudflare {
	interface GlobalProps {
		mainModule: typeof import("./dist/server/index");
	}
	interface Env extends __BaseEnv_Env {}
}
interface Env extends __BaseEnv_Env {}
type StringifyValues<EnvType extends Record<string, unknown>> = {
	[Binding in keyof EnvType]: EnvType[Binding] extends string ? EnvType[Binding] : string;
};
declare namespace NodeJS {
	interface ProcessEnv extends StringifyValues<Pick<Cloudflare.Env, "CRM_AUTH_USERNAME">> {}
}
