/* eslint-disable */
// Generated by Wrangler by running `wrangler types --include-runtime=false` (hash: 56f46fea4ea0e289f5bc459a9a10d83c)
interface __BaseEnv_Env {
	EMAIL_FILES: R2Bucket;
	ASSETS: Fetcher;
}
declare namespace Cloudflare {
	interface GlobalProps {
		mainModule: typeof import("./dist/server/index");
	}
	interface Env extends __BaseEnv_Env {}
}
interface Env extends __BaseEnv_Env {}
