/* eslint-disable */
// Generated by Wrangler by running `wrangler types worker-configuration.d.ts --config dist/server/wrangler.json --include-runtime false` (hash: 3bc13101947520f8278541fa8f2c3eb6)
interface __BaseEnv_Env {
	EMAIL_FILES: R2Bucket;
	DB: D1Database;
	AI: Ai;
	ASSETS: Fetcher;
	LoriotSalesAgent: DurableObjectNamespace<import("./dist/server/index").LoriotSalesAgent>;
}
declare namespace Cloudflare {
	interface GlobalProps {
		mainModule: typeof import("./dist/server/index");
		durableNamespaces: "LoriotSalesAgent";
	}
	interface Env extends __BaseEnv_Env {}
}
interface Env extends __BaseEnv_Env {}
