import { index, integer, real, sqliteTable, text, uniqueIndex } from "drizzle-orm/sqlite-core";

export const accounts = sqliteTable("accounts", {
  id: text("id").primaryKey(),
  customerCode: text("customer_code").notNull().default(""),
  companyName: text("company_name").notNull(),
  accountType: text("account_type").notNull(),
  industry: text("industry").notNull().default(""),
  region: text("region").notNull().default(""),
  website: text("website").notNull().default(""),
  owner: text("owner").notNull().default("Sales Fluke"),
  notes: text("notes").notNull().default(""),
  createdAt: text("created_at").notNull(),
  updatedAt: text("updated_at").notNull(),
}, (table) => [
  index("idx_accounts_customer_code").on(table.customerCode),
]);

export const contacts = sqliteTable("contacts", {
  id: text("id").primaryKey(),
  accountId: text("account_id").notNull().references(() => accounts.id),
  fullName: text("full_name").notNull(),
  title: text("title").notNull().default(""),
  department: text("department").notNull().default(""),
  buyingRole: text("buying_role").notNull().default(""),
  phone: text("phone").notNull().default(""),
  email: text("email").notNull().default(""),
  zalo: text("zalo").notNull().default(""),
  preferredChannel: text("preferred_channel").notNull().default(""),
  createdAt: text("created_at").notNull(),
  updatedAt: text("updated_at").notNull(),
});

export const prospectingLeads = sqliteTable("prospecting_leads", {
  id: text("id").primaryKey(),
  companyName: text("company_name").notNull(),
  website: text("website").notNull().default(""),
  industry: text("industry").notNull().default(""),
  accountType: text("account_type").notNull().default("End-User"),
  contactName: text("contact_name").notNull().default(""),
  title: text("title").notNull().default(""),
  email: text("email").notNull().default(""),
  phone: text("phone").notNull().default(""),
  source: text("source").notNull().default(""),
  lastEmailDate: text("last_email_date").notNull().default(""),
  status: text("status").notNull().default("Chưa gửi"),
  nextFollowUpDate: text("next_follow_up_date").notNull().default(""),
  emailSubject: text("email_subject").notNull().default(""),
  replyNotes: text("reply_notes").notNull().default(""),
  notes: text("notes").notNull().default(""),
  owner: text("owner").notNull().default("Mai Trần Thành"),
  emailOptOut: integer("email_opt_out").notNull().default(0),
  convertedOpportunityId: text("converted_opportunity_id").notNull().default(""),
  convertedAt: text("converted_at").notNull().default(""),
  createdAt: text("created_at").notNull(),
  updatedAt: text("updated_at").notNull(),
}, (table) => [
  index("idx_prospecting_leads_status").on(table.status),
  index("idx_prospecting_leads_follow_up").on(table.nextFollowUpDate),
  index("idx_prospecting_leads_email").on(table.email),
]);

export const emailSettings = sqliteTable("email_settings", {
  id: text("id").primaryKey(),
  fromEmail: text("from_email").notNull(),
  fromName: text("from_name").notNull().default("Mai Trần Thành"),
  username: text("username").notNull(),
  smtpHost: text("smtp_host").notNull().default("pro43.emailserver.vn"),
  smtpPort: integer("smtp_port").notNull().default(465),
  smtpSecurity: text("smtp_security").notNull().default("ssl"),
  imapHost: text("imap_host").notNull().default("pro43.emailserver.vn"),
  imapPort: integer("imap_port").notNull().default(993),
  passwordCiphertext: text("password_ciphertext").notNull().default(""),
  passwordIv: text("password_iv").notNull().default(""),
  defaultSubject: text("default_subject").notNull().default(""),
  defaultBody: text("default_body").notNull().default(""),
  updatedAt: text("updated_at").notNull(),
});

export const emailAssets = sqliteTable("email_assets", {
  id: text("id").primaryKey(),
  objectKey: text("object_key").notNull().unique(),
  fileName: text("file_name").notNull(),
  contentType: text("content_type").notNull(),
  sizeBytes: integer("size_bytes").notNull().default(0),
  fileKind: text("file_kind").notNull().default("document"),
  createdAt: text("created_at").notNull(),
}, (table) => [index("idx_email_assets_created").on(table.createdAt)]);

export const emailMessages = sqliteTable("email_messages", {
  id: text("id").primaryKey(),
  leadId: text("lead_id").notNull().references(() => prospectingLeads.id, { onDelete: "cascade" }),
  direction: text("direction").notNull(),
  senderEmail: text("sender_email").notNull().default(""),
  recipientEmail: text("recipient_email").notNull().default(""),
  subject: text("subject").notNull().default(""),
  bodyText: text("body_text").notNull().default(""),
  status: text("status").notNull().default("Queued"),
  campaignId: text("campaign_id").notNull().default(""),
  classification: text("classification").notNull().default(""),
  aiSummary: text("ai_summary").notNull().default(""),
  suggestedAction: text("suggested_action").notNull().default(""),
  draftReply: text("draft_reply").notNull().default(""),
  aiConfidence: real("ai_confidence").notNull().default(0),
  aiSource: text("ai_source").notNull().default(""),
  aiProcessedAt: text("ai_processed_at").notNull().default(""),
  providerMessageId: text("provider_message_id").notNull().default(""),
  errorMessage: text("error_message").notNull().default(""),
  sentAt: text("sent_at").notNull().default(""),
  receivedAt: text("received_at").notNull().default(""),
  createdAt: text("created_at").notNull(),
}, (table) => [
  index("idx_email_messages_lead_created").on(table.leadId, table.createdAt),
  uniqueIndex("idx_email_messages_provider_id").on(table.providerMessageId),
]);

export const emailAutomationSettings = sqliteTable("email_automation_settings", {
  id: text("id").primaryKey(),
  enabled: integer("enabled").notNull().default(0),
  dailyLimit: integer("daily_limit").notNull().default(20),
  batchSize: integer("batch_size").notNull().default(2),
  sendStartHour: integer("send_start_hour").notNull().default(8),
  sendEndHour: integer("send_end_hour").notNull().default(17),
  weekdaysOnly: integer("weekdays_only").notNull().default(1),
  autoClassifyReplies: integer("auto_classify_replies").notNull().default(1),
  updatedAt: text("updated_at").notNull(),
});

export const emailCampaigns = sqliteTable("email_campaigns", {
  id: text("id").primaryKey(),
  name: text("name").notNull(),
  objective: text("objective").notNull().default(""),
  status: text("status").notNull().default("Draft"),
  startDate: text("start_date").notNull(),
  subjectTemplate: text("subject_template").notNull(),
  bodyTemplate: text("body_template").notNull(),
  followUpEnabled: integer("follow_up_enabled").notNull().default(0),
  followUpDelayDays: integer("follow_up_delay_days").notNull().default(4),
  followUpSubjectTemplate: text("follow_up_subject_template").notNull().default(""),
  followUpBodyTemplate: text("follow_up_body_template").notNull().default(""),
  industryTemplateId: text("industry_template_id").notNull().default(""),
  industryGroup: text("industry_group").notNull().default(""),
  sequenceJson: text("sequence_json").notNull().default("[]"),
  assetIdsJson: text("asset_ids_json").notNull().default("[]"),
  createdAt: text("created_at").notNull(),
  updatedAt: text("updated_at").notNull(),
}, (table) => [index("idx_email_campaigns_status_start").on(table.status, table.startDate)]);

export const emailCampaignRecipients = sqliteTable("email_campaign_recipients", {
  id: text("id").primaryKey(),
  campaignId: text("campaign_id").notNull().references(() => emailCampaigns.id, { onDelete: "cascade" }),
  leadId: text("lead_id").notNull().references(() => prospectingLeads.id, { onDelete: "cascade" }),
  status: text("status").notNull().default("Queued"),
  currentStep: integer("current_step").notNull().default(0),
  nextSendAt: text("next_send_at").notNull().default(""),
  sentAt: text("sent_at").notNull().default(""),
  repliedAt: text("replied_at").notNull().default(""),
  attempts: integer("attempts").notNull().default(0),
  lastError: text("last_error").notNull().default(""),
  emailMessageId: text("email_message_id").notNull().default(""),
  createdAt: text("created_at").notNull(),
  updatedAt: text("updated_at").notNull(),
}, (table) => [
  uniqueIndex("idx_email_campaign_recipient_unique").on(table.campaignId, table.leadId),
  index("idx_email_campaign_recipient_queue").on(table.status, table.nextSendAt),
  index("idx_email_campaign_recipient_lead").on(table.leadId),
]);

export const emailAutomationRuns = sqliteTable("email_automation_runs", {
  id: text("id").primaryKey(),
  runType: text("run_type").notNull().default("Scheduled"),
  status: text("status").notNull().default("Running"),
  repliesAdded: integer("replies_added").notNull().default(0),
  sentCount: integer("sent_count").notNull().default(0),
  failedCount: integer("failed_count").notNull().default(0),
  errorMessage: text("error_message").notNull().default(""),
  startedAt: text("started_at").notNull(),
  completedAt: text("completed_at").notNull().default(""),
}, (table) => [index("idx_email_automation_runs_started").on(table.startedAt)]);

export const opportunities = sqliteTable("opportunities", {
  id: text("id").primaryKey(),
  accountId: text("account_id").notNull().references(() => accounts.id),
  contactId: text("contact_id").notNull().references(() => contacts.id),
  productApplication: text("product_application").notNull(),
  needPain: text("need_pain").notNull().default(""),
  stage: text("stage").notNull().default("Target Account"),
  status: text("status").notNull().default("Open"),
  estimatedValue: integer("estimated_value").notNull().default(0),
  expectedCloseDate: text("expected_close_date").notNull().default(""),
  actualCloseDate: text("actual_close_date").notNull().default(""),
  lastContactDate: text("last_contact_date").notNull().default(""),
  nextStep: text("next_step").notNull().default(""),
  nextStepDue: text("next_step_due").notNull().default(""),
  owner: text("owner").notNull().default("Sales Fluke"),
  icpFit: integer("icp_fit").notNull().default(0),
  needScore: integer("need_score").notNull().default(0),
  authorityScore: integer("authority_score").notNull().default(0),
  budgetScore: integer("budget_score").notNull().default(0),
  timingScore: integer("timing_score").notNull().default(0),
  engagementScore: integer("engagement_score").notNull().default(0),
  channelScore: integer("channel_score").notNull().default(0),
  competitor: text("competitor").notNull().default(""),
  lostReason: text("lost_reason").notNull().default(""),
  notes: text("notes").notNull().default(""),
  endUserCompany: text("end_user_company").notNull().default(""),
  endUserAddress: text("end_user_address").notNull().default(""),
  endUserIndustry: text("end_user_industry").notNull().default(""),
  endUserContactName: text("end_user_contact_name").notNull().default(""),
  endUserTitle: text("end_user_title").notNull().default(""),
  endUserPhone: text("end_user_phone").notNull().default(""),
  endUserEmail: text("end_user_email").notNull().default(""),
  endUserNotes: text("end_user_notes").notNull().default(""),
  stageEnteredAt: text("stage_entered_at").notNull(),
  createdAt: text("created_at").notNull(),
  updatedAt: text("updated_at").notNull(),
});

export const quotations = sqliteTable("quotations", {
  id: text("id").primaryKey(),
  opportunityId: text("opportunity_id").notNull().references(() => opportunities.id),
  quotationNo: text("quotation_no").notNull().unique(),
  quoteDate: text("quote_date").notNull(),
  expirationDate: text("expiration_date").notNull().default(""),
  customerId: text("customer_id").notNull().default(""),
  recipientCompany: text("recipient_company").notNull(),
  recipientAddress: text("recipient_address").notNull().default(""),
  attention: text("attention").notNull().default(""),
  recipientEmail: text("recipient_email").notNull().default(""),
  shippingMethod: text("shipping_method").notNull().default("Air Shipment"),
  shippingTerms: text("shipping_terms").notNull().default("DDP"),
  deliveryDate: text("delivery_date").notNull().default("2-4 Weeks"),
  paymentTerms: text("payment_terms").notNull().default("100% TT"),
  currency: text("currency").notNull().default("VND"),
  vatRate: integer("vat_rate").notNull().default(8),
  preparedBy: text("prepared_by").notNull().default("MAI TRẦN THÀNH (+84 964 72 72 33)"),
  status: text("status").notNull().default("Draft"),
  notes: text("notes").notNull().default(""),
  subtotal: integer("subtotal").notNull().default(0),
  vatAmount: integer("vat_amount").notNull().default(0),
  total: integer("total").notNull().default(0),
  createdAt: text("created_at").notNull(),
  updatedAt: text("updated_at").notNull(),
});

export const quotationItems = sqliteTable("quotation_items", {
  id: text("id").primaryKey(),
  quotationId: text("quotation_id").notNull().references(() => quotations.id),
  lineNo: integer("line_no").notNull(),
  itemNumber: text("item_number").notNull().default(""),
  description: text("description").notNull(),
  application: text("application").notNull().default(""),
  unit: text("unit").notNull().default("PCS"),
  quantity: real("quantity").notNull().default(1),
  productId: text("product_id").notNull().default(""),
  listPrice: integer("list_price").notNull().default(0),
  discountPercent: real("discount_percent").notNull().default(0),
  origin: text("origin").notNull().default(""),
  warranty: text("warranty").notNull().default("12 tháng"),
  unitPrice: integer("unit_price").notNull().default(0),
  amount: integer("amount").notNull().default(0),
});

export const products = sqliteTable("products", {
  id: text("id").primaryKey(),
  productFamily: text("product_family").notNull().default(""),
  modelGroup: text("model_group").notNull().default(""),
  marketModel: text("market_model").notNull().default(""),
  model: text("model").notNull(),
  normalizedModel: text("normalized_model").notNull(),
  itemNo: text("item_no").notNull().unique(),
  description: text("description").notNull().default(""),
  countryOfOrigin: text("country_of_origin").notNull().default(""),
  listPriceUsd: real("list_price_usd").notNull().default(0),
  listPriceVnd: integer("list_price_vnd").notNull().default(0),
  itemStatus: text("item_status").notNull().default("ACTIVE"),
  grossWeight: text("gross_weight").notNull().default(""),
  uom: text("uom").notNull().default("EA"),
  warrantyText: text("warranty_text").notNull().default("12 tháng"),
  highTouch: integer("high_touch").notNull().default(0),
  priceSource: text("price_source").notNull().default(""),
  highTouchSource: text("high_touch_source").notNull().default(""),
  updatedAt: text("updated_at").notNull(),
}, (table) => [
  index("idx_products_model").on(table.normalizedModel),
  index("idx_products_high_touch").on(table.highTouch),
]);

export const pricingSettings = sqliteTable("pricing_settings", {
  id: text("id").primaryKey(),
  useManualRate: integer("use_manual_rate").notNull().default(0),
  manualRate: real("manual_rate").notNull().default(0),
  bufferPercent: real("buffer_percent").notNull().default(0),
  roundingStep: integer("rounding_step").notNull().default(1000),
  lastLiveRate: real("last_live_rate").notNull().default(26310),
  sourceUpdatedAt: text("source_updated_at").notNull().default(""),
  fetchedAt: text("fetched_at").notNull().default(""),
  updatedAt: text("updated_at").notNull(),
});

export const inventoryItems = sqliteTable("inventory_items", {
  id: text("id").primaryKey(),
  productId: text("product_id").notNull().default(""),
  materialCode: text("material_code").notNull().unique(),
  itemNo: text("item_no").notNull().default(""),
  description: text("description").notNull().default(""),
  unit: text("unit").notNull().default("Bộ"),
  quantity: real("quantity").notNull().default(0),
  reportDate: text("report_date").notNull().default(""),
  sourceFile: text("source_file").notNull().default(""),
  updatedAt: text("updated_at").notNull(),
}, (table) => [
  index("idx_inventory_item_no").on(table.itemNo),
  index("idx_inventory_product").on(table.productId),
]);

export const weeklyReports = sqliteTable("weekly_reports", {
  id: text("id").primaryKey(),
  weekStart: text("week_start").notNull().unique(),
  weekEnd: text("week_end").notNull(),
  reportDate: text("report_date").notNull(),
  weekNumber: integer("week_number").notNull(),
  reporter: text("reporter").notNull().default("Mai Trần Thành"),
  status: text("status").notNull().default("Draft"),
  sourceFile: text("source_file").notNull().default(""),
  planJson: text("plan_json").notNull().default("[]"),
  projectsJson: text("projects_json").notNull().default("[]"),
  createdAt: text("created_at").notNull(),
  updatedAt: text("updated_at").notNull(),
}, (table) => [index("idx_weekly_reports_week").on(table.weekStart)]);

export const activities = sqliteTable("activities", {
  id: text("id").primaryKey(),
  opportunityId: text("opportunity_id").notNull().references(() => opportunities.id),
  activityDate: text("activity_date").notNull(),
  activityType: text("activity_type").notNull(),
  contactName: text("contact_name").notNull().default(""),
  summary: text("summary").notNull(),
  outcome: text("outcome").notNull().default(""),
  nextStep: text("next_step").notNull().default(""),
  dueDate: text("due_date").notNull().default(""),
  owner: text("owner").notNull().default("Sales Fluke"),
  status: text("status").notNull().default("Completed"),
  includeInWeeklyReport: integer("include_in_weekly_report").notNull().default(0),
  createdAt: text("created_at").notNull(),
  updatedAt: text("updated_at").notNull().default(""),
});
