import { index, integer, real, sqliteTable, text } from "drizzle-orm/sqlite-core";

export const accounts = sqliteTable("accounts", {
  id: text("id").primaryKey(),
  customerCode: text("customer_code").notNull().default(""),
  companyName: text("company_name").notNull(),
  accountType: text("account_type").notNull(),
  industry: text("industry").notNull().default(""),
  region: text("region").notNull().default(""),
  website: text("website").notNull().default(""),
  owner: text("owner").notNull().default("Sales Fluke"),
  notes: text("notes").notNull().default(""),
  createdAt: text("created_at").notNull(),
  updatedAt: text("updated_at").notNull(),
}, (table) => [
  index("idx_accounts_customer_code").on(table.customerCode),
]);

export const contacts = sqliteTable("contacts", {
  id: text("id").primaryKey(),
  accountId: text("account_id").notNull().references(() => accounts.id),
  fullName: text("full_name").notNull(),
  title: text("title").notNull().default(""),
  department: text("department").notNull().default(""),
  buyingRole: text("buying_role").notNull().default(""),
  phone: text("phone").notNull().default(""),
  email: text("email").notNull().default(""),
  zalo: text("zalo").notNull().default(""),
  preferredChannel: text("preferred_channel").notNull().default(""),
  createdAt: text("created_at").notNull(),
  updatedAt: text("updated_at").notNull(),
});

export const opportunities = sqliteTable("opportunities", {
  id: text("id").primaryKey(),
  accountId: text("account_id").notNull().references(() => accounts.id),
  contactId: text("contact_id").notNull().references(() => contacts.id),
  productApplication: text("product_application").notNull(),
  needPain: text("need_pain").notNull().default(""),
  stage: text("stage").notNull().default("Target Account"),
  status: text("status").notNull().default("Open"),
  estimatedValue: integer("estimated_value").notNull().default(0),
  expectedCloseDate: text("expected_close_date").notNull().default(""),
  actualCloseDate: text("actual_close_date").notNull().default(""),
  lastContactDate: text("last_contact_date").notNull().default(""),
  nextStep: text("next_step").notNull().default(""),
  nextStepDue: text("next_step_due").notNull().default(""),
  owner: text("owner").notNull().default("Sales Fluke"),
  icpFit: integer("icp_fit").notNull().default(0),
  needScore: integer("need_score").notNull().default(0),
  authorityScore: integer("authority_score").notNull().default(0),
  budgetScore: integer("budget_score").notNull().default(0),
  timingScore: integer("timing_score").notNull().default(0),
  engagementScore: integer("engagement_score").notNull().default(0),
  channelScore: integer("channel_score").notNull().default(0),
  competitor: text("competitor").notNull().default(""),
  lostReason: text("lost_reason").notNull().default(""),
  notes: text("notes").notNull().default(""),
  endUserCompany: text("end_user_company").notNull().default(""),
  endUserAddress: text("end_user_address").notNull().default(""),
  endUserIndustry: text("end_user_industry").notNull().default(""),
  endUserContactName: text("end_user_contact_name").notNull().default(""),
  endUserTitle: text("end_user_title").notNull().default(""),
  endUserPhone: text("end_user_phone").notNull().default(""),
  endUserEmail: text("end_user_email").notNull().default(""),
  endUserNotes: text("end_user_notes").notNull().default(""),
  stageEnteredAt: text("stage_entered_at").notNull(),
  createdAt: text("created_at").notNull(),
  updatedAt: text("updated_at").notNull(),
});

export const quotations = sqliteTable("quotations", {
  id: text("id").primaryKey(),
  opportunityId: text("opportunity_id").notNull().references(() => opportunities.id),
  quotationNo: text("quotation_no").notNull().unique(),
  quoteDate: text("quote_date").notNull(),
  expirationDate: text("expiration_date").notNull().default(""),
  customerId: text("customer_id").notNull().default(""),
  recipientCompany: text("recipient_company").notNull(),
  recipientAddress: text("recipient_address").notNull().default(""),
  attention: text("attention").notNull().default(""),
  recipientEmail: text("recipient_email").notNull().default(""),
  shippingMethod: text("shipping_method").notNull().default("Air Shipment"),
  shippingTerms: text("shipping_terms").notNull().default("DDP"),
  deliveryDate: text("delivery_date").notNull().default("2-4 Weeks"),
  paymentTerms: text("payment_terms").notNull().default("100% TT"),
  currency: text("currency").notNull().default("VND"),
  vatRate: integer("vat_rate").notNull().default(8),
  preparedBy: text("prepared_by").notNull().default("MAI TRẦN THÀNH (+84 964 72 72 33)"),
  status: text("status").notNull().default("Draft"),
  notes: text("notes").notNull().default(""),
  subtotal: integer("subtotal").notNull().default(0),
  vatAmount: integer("vat_amount").notNull().default(0),
  total: integer("total").notNull().default(0),
  createdAt: text("created_at").notNull(),
  updatedAt: text("updated_at").notNull(),
});

export const quotationItems = sqliteTable("quotation_items", {
  id: text("id").primaryKey(),
  quotationId: text("quotation_id").notNull().references(() => quotations.id),
  lineNo: integer("line_no").notNull(),
  itemNumber: text("item_number").notNull().default(""),
  description: text("description").notNull(),
  application: text("application").notNull().default(""),
  unit: text("unit").notNull().default("PCS"),
  quantity: real("quantity").notNull().default(1),
  productId: text("product_id").notNull().default(""),
  listPrice: integer("list_price").notNull().default(0),
  discountPercent: real("discount_percent").notNull().default(0),
  origin: text("origin").notNull().default(""),
  warranty: text("warranty").notNull().default("12 tháng"),
  unitPrice: integer("unit_price").notNull().default(0),
  amount: integer("amount").notNull().default(0),
});

export const products = sqliteTable("products", {
  id: text("id").primaryKey(),
  productFamily: text("product_family").notNull().default(""),
  modelGroup: text("model_group").notNull().default(""),
  marketModel: text("market_model").notNull().default(""),
  model: text("model").notNull(),
  normalizedModel: text("normalized_model").notNull(),
  itemNo: text("item_no").notNull().unique(),
  description: text("description").notNull().default(""),
  countryOfOrigin: text("country_of_origin").notNull().default(""),
  listPriceUsd: real("list_price_usd").notNull().default(0),
  listPriceVnd: integer("list_price_vnd").notNull().default(0),
  itemStatus: text("item_status").notNull().default("ACTIVE"),
  grossWeight: text("gross_weight").notNull().default(""),
  uom: text("uom").notNull().default("EA"),
  warrantyText: text("warranty_text").notNull().default("12 tháng"),
  highTouch: integer("high_touch").notNull().default(0),
  priceSource: text("price_source").notNull().default(""),
  highTouchSource: text("high_touch_source").notNull().default(""),
  updatedAt: text("updated_at").notNull(),
}, (table) => [
  index("idx_products_model").on(table.normalizedModel),
  index("idx_products_high_touch").on(table.highTouch),
]);

export const pricingSettings = sqliteTable("pricing_settings", {
  id: text("id").primaryKey(),
  useManualRate: integer("use_manual_rate").notNull().default(0),
  manualRate: real("manual_rate").notNull().default(0),
  bufferPercent: real("buffer_percent").notNull().default(0),
  roundingStep: integer("rounding_step").notNull().default(1000),
  lastLiveRate: real("last_live_rate").notNull().default(26310),
  sourceUpdatedAt: text("source_updated_at").notNull().default(""),
  fetchedAt: text("fetched_at").notNull().default(""),
  updatedAt: text("updated_at").notNull(),
});

export const inventoryItems = sqliteTable("inventory_items", {
  id: text("id").primaryKey(),
  productId: text("product_id").notNull().default(""),
  materialCode: text("material_code").notNull().unique(),
  itemNo: text("item_no").notNull().default(""),
  description: text("description").notNull().default(""),
  unit: text("unit").notNull().default("Bộ"),
  quantity: real("quantity").notNull().default(0),
  reportDate: text("report_date").notNull().default(""),
  sourceFile: text("source_file").notNull().default(""),
  updatedAt: text("updated_at").notNull(),
}, (table) => [
  index("idx_inventory_item_no").on(table.itemNo),
  index("idx_inventory_product").on(table.productId),
]);

export const weeklyReports = sqliteTable("weekly_reports", {
  id: text("id").primaryKey(),
  weekStart: text("week_start").notNull().unique(),
  weekEnd: text("week_end").notNull(),
  reportDate: text("report_date").notNull(),
  weekNumber: integer("week_number").notNull(),
  reporter: text("reporter").notNull().default("Mai Trần Thành"),
  status: text("status").notNull().default("Draft"),
  sourceFile: text("source_file").notNull().default(""),
  planJson: text("plan_json").notNull().default("[]"),
  projectsJson: text("projects_json").notNull().default("[]"),
  createdAt: text("created_at").notNull(),
  updatedAt: text("updated_at").notNull(),
}, (table) => [index("idx_weekly_reports_week").on(table.weekStart)]);

export const activities = sqliteTable("activities", {
  id: text("id").primaryKey(),
  opportunityId: text("opportunity_id").notNull().references(() => opportunities.id),
  activityDate: text("activity_date").notNull(),
  activityType: text("activity_type").notNull(),
  contactName: text("contact_name").notNull().default(""),
  summary: text("summary").notNull(),
  outcome: text("outcome").notNull().default(""),
  nextStep: text("next_step").notNull().default(""),
  dueDate: text("due_date").notNull().default(""),
  owner: text("owner").notNull().default("Sales Fluke"),
  createdAt: text("created_at").notNull(),
});
